name: Build And Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: deploy-test
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          docker build -t deploy-test:latest .
      - name: push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          