name: Build And Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: deploy-test
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u TOnodera --password-stdin

      - name: Set version
        id: version
        run: |
          echo ::set-output name=version::${GITHUB_REF##*/}

      - name: build
        run: |
          docker build -t ghcr.io/tonodera/deploy-test:${{ steps.version.outputs.VERSION }} .

      - name: docker push
        run: |
          docker push ghcr.io/tonodera/deploy-test:${{ steps.version.outputs.VERSION }}
          